//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirzaeva.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int account_id { get; set; }
        public string account_login { get; set; }
        public string account_password { get; set; }
    }
}
