//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirzaeva.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barber
    {
        public Barber()
        {
            this.Records = new HashSet<Records>();
        }
    
        public int barber_Id { get; set; }
        public string barber_name { get; set; }
        public string barber_post { get; set; }
        public string barber_info { get; set; }
        public byte[] barber_photo { get; set; }
    
        public virtual ICollection<Records> Records { get; set; }
    }
}
