//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirzaeva.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int record_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> barber_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<System.DateTime> reccord_date_and_time { get; set; }
        public string record_coment { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Service Service { get; set; }
    }
}
